/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as EulaRouteImport } from './routes/eula'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedVendorsRouteImport } from './routes/_authed.vendors'
import { Route as AuthedTeamRouteImport } from './routes/_authed.team'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedProjectsRouteImport } from './routes/_authed.projects'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed.invoices'
import { Route as AuthedAuditRouteImport } from './routes/_authed.audit'
import { Route as AuthedInvoicesIdRouteImport } from './routes/_authed.invoices_.$id'

const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const EulaRoute = EulaRouteImport.update({
  id: '/eula',
  path: '/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVendorsRoute = AuthedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamRoute = AuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesIdRoute = AuthedInvoicesIdRouteImport.update({
  id: '/invoices_/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/eula': typeof EulaRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/audit': typeof AuthedAuditRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/projects': typeof AuthedProjectsRoute
  '/settings': typeof AuthedSettingsRoute
  '/team': typeof AuthedTeamRoute
  '/vendors': typeof AuthedVendorsRoute
  '/invoices/$id': typeof AuthedInvoicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/eula': typeof EulaRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/audit': typeof AuthedAuditRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/projects': typeof AuthedProjectsRoute
  '/settings': typeof AuthedSettingsRoute
  '/team': typeof AuthedTeamRoute
  '/vendors': typeof AuthedVendorsRoute
  '/invoices/$id': typeof AuthedInvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/eula': typeof EulaRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/projects': typeof AuthedProjectsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/team': typeof AuthedTeamRoute
  '/_authed/vendors': typeof AuthedVendorsRoute
  '/_authed/invoices_/$id': typeof AuthedInvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/eula'
    | '/invite'
    | '/privacy'
    | '/audit'
    | '/invoices'
    | '/projects'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/eula'
    | '/invite'
    | '/privacy'
    | '/audit'
    | '/invoices'
    | '/projects'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/invoices/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/callback'
    | '/eula'
    | '/invite'
    | '/privacy'
    | '/_authed/audit'
    | '/_authed/invoices'
    | '/_authed/projects'
    | '/_authed/settings'
    | '/_authed/team'
    | '/_authed/vendors'
    | '/_authed/invoices_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  EulaRoute: typeof EulaRoute
  InviteRoute: typeof InviteRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eula': {
      id: '/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof EulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vendors': {
      id: '/_authed/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthedVendorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/team': {
      id: '/_authed/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthedTeamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices_/$id': {
      id: '/_authed/invoices_/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthedInvoicesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedProjectsRoute: typeof AuthedProjectsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTeamRoute: typeof AuthedTeamRoute
  AuthedVendorsRoute: typeof AuthedVendorsRoute
  AuthedInvoicesIdRoute: typeof AuthedInvoicesIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTeamRoute: AuthedTeamRoute,
  AuthedVendorsRoute: AuthedVendorsRoute,
  AuthedInvoicesIdRoute: AuthedInvoicesIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  EulaRoute: EulaRoute,
  InviteRoute: InviteRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
